Repository Team-SSEUDAM/Sseudam-iOS, pull requests merged in 2025-08, with the labels that each got.

#75 쓰레기통 디테일 캐시
  .gitignore
  Projects/Core/Cache/Sources/CacheActor.swift
  Projects/Core/Cache/Sources/CacheComponent/CacheKey.swift
  Projects/Core/Cache/Sources/CacheModel/TrashDetailCacheModel.swift
  Projects/Data/TrashSpot/TrashSpotData/Sources/TrashSpotRepositoryImpl.swift
  Projects/Domain/TrashSpot/TrashSpotDomain/Sources/FetchTrashSpotDetailUseCaseImpl.swift
  Projects/Domain/TrashSpot/TrashSpotDomainInterface/Sources/Entity/TrashSpotDetailEntity.swift
  Projects/Domain/TrashSpot/TrashSpotDomainInterface/Sources/TrashSpotRepository.swift
Labels: feature

#76 출석 애니메이션 적용
  Projects/Core/DesignKit/Sources/Component/LevelBar/LevelBar.swift
  Projects/Core/DesignKit/Sources/Resource+/Cat+.swift
  Projects/Feature/Attendance/AttendanceFeature/Sources/AttendanceFeature.swift
  Projects/Feature/Attendance/AttendanceFeature/Sources/AttendanceStatus.swift
  Projects/Feature/Attendance/AttendanceFeature/Sources/AttendanceView.swift
  Projects/Shared/Utility/Sources/Type/SseudamPoint.swift
  Projects/Sseudam/Sources/Feature/UserEntryFeature.swift
Labels: feature

#89 hotfix: #88 마이페이지 스크롤 안되는 현상 수정
  Projects/Feature/MyPage/MyPageFeature/Sources/Views/MyPageView.swift
Labels: hotfix

#100 레벨업 화면 구현
  Projects/Core/DesignKit/Sources/Component/LevelBar/LevelBar.swift
  Projects/Domain/Pet/PetDomain/Sources/CheckPetInfoUseCaseImpl.swift
  Projects/Feature/LevelUp/LevelUpFeature/Sources/LevelUpFeature.swift
  Projects/Feature/LevelUp/LevelUpFeature/Sources/LevelUpView.swift
  Projects/Feature/LevelUp/LevelUpFeatureDemo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/Feature/LevelUp/LevelUpFeatureDemo/Resources/Assets.xcassets/Contents.json
  Projects/Feature/LevelUp/LevelUpFeatureDemo/Sources/LevelUpDemoApp.swift
  Projects/Feature/LevelUp/LevelUpFeatureTesting/Sources/LevelUpUnitTests.swift
  Projects/Feature/LevelUp/Project.swift
  Projects/Feature/Project.swift
  Projects/Feature/TrashDetail/TrashDetailFeature/Sources/Features/VisitedFeature.swift
  Projects/Shared/UserDefaults/Sources/UserDefaultsKeys.swift
  Projects/Sseudam/Sources/Feature/UserEntryFeature.swift
  Projects/Sseudam/Sources/SseudamView.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+.swift
Labels: feature

#102 Qa/#101 2차 디자인 QA 및 기능 개선
  Projects/Core/DesignKit/Resources/Colors.xcassets/HexColor/A3D9FF.colorset/Contents.json
  Projects/Core/DesignKit/Resources/Colors.xcassets/HexColor/D7E4F8.colorset/Contents.json
  Projects/Core/DesignKit/Sources/Component/CheckBoxButton/CheckBoxButton.swift
  Projects/Core/DesignKit/Sources/Resource+/Color+.swift
  Projects/Data/History/HistoryDataInterface/Sources/DTO/SuggestionAndReportHistoryDTO.swift
  Projects/Feature/MyPage/MyPageFeature/Sources/Views/SuggestionList/SuggestCell.swift
  Projects/Feature/MyPet/MyPetFeature/Sources/Features/MyPetGrowthListFeature.swift
  Projects/Feature/MyPet/MyPetFeature/Sources/Views/Cells/CatCardCell.swift
  Projects/Feature/MyPet/MyPetFeature/Sources/Views/Cells/GrowthRecordCell.swift
  Projects/Feature/MyPet/MyPetFeature/Sources/Views/MyPetCardView.swift
  Projects/Feature/MyPet/MyPetFeature/Sources/Views/MyPetGrowthListView.swift
  Projects/Feature/MyPet/MyPetFeature/Sources/Views/MyPetView.swift
Labels: qa

#103 쓰레기통 디테일 및 지도 레이아웃 qa 반영
  Projects/Core/DesignKit/Sources/Component/Badge/Badge.swift
  Projects/Core/NetworkKit/Sources/Implementation/Interceptor.swift
  Projects/Feature/Home/HomeFeature/Sources/View/HomeView.swift
  Projects/Feature/TrashDetail/TrashDetailFeature/Sources/Views/TrashDetailView.swift
Labels: qa
